spring:
  security:
    user:
      name: name
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/DBDAYONE
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true